from fpdf import FPDF
from datetime import datetime
import io

class ClinicalReportPDF(FPDF):
    def header(self):
        # Logo placeholder or Title
        self.set_font("Helvetica", "B", 20)
        self.set_text_color(37, 99, 235) # Clinical Blue
        self.cell(0, 10, "LittleHeart AI Care - Clinical Report", ln=True, align="C")
        self.set_font("Helvetica", "I", 10)
        self.set_text_color(100)
        self.cell(0, 10, f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True, align="C")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128)
        self.cell(0, 10, f"Page {self.page_no()} | CONFIDENTIAL CLINICAL DATA", align="C")

def generate_clinical_pdf(patient_data: dict, result_data: dict) -> bytes:
    pdf = ClinicalReportPDF()
    pdf.add_page()
    
    # --- Patient Summary ---
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(0)
    pdf.cell(0, 10, "1. Patient Summary", ln=True)
    pdf.set_font("Helvetica", "", 11)
    
    summary_lines = [
        f"Age: {patient_data.get('age')}",
        f"Trimester: {patient_data.get('trimester')} (Week {patient_data.get('trimester_weeks')})",
        f"Blood Pressure: {patient_data.get('blood_pressure_systolic')}/{patient_data.get('blood_pressure_diastolic')} mmHg",
        f"Hemoglobin: {patient_data.get('hemoglobin')} g/dL",
        f"Heart Rate: {patient_data.get('heart_rate')} bpm"
    ]
    for line in summary_lines:
        pdf.cell(0, 7, f"- {line}", ln=True)
    
    pdf.ln(5)
    
    # --- Risk Assessment ---
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "2. AI Risk Assessment", ln=True)
    
    risk_level = result_data.get("final_risk", "UNKNOWN")
    confidence = result_data.get("clinical_confidence", 0)
    display_conf = confidence * 100 if confidence <= 1.0 else confidence
    
    pdf.set_font("Helvetica", "B", 12)
    # Background color based on risk
    if risk_level in ["HIGH", "CRITICAL"]:
        pdf.set_fill_color(254, 226, 226) # Light Red
        pdf.set_text_color(153, 27, 27) # Dark Red
    else:
        pdf.set_fill_color(240, 253, 244) # Light Green
        pdf.set_text_color(22, 101, 52) # Dark Green
        
    pdf.cell(0, 10, f"FINAL RISK LEVEL: {risk_level}", ln=True, fill=True, border=1)
    
    pdf.set_text_color(0)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 10, f"Clinical Confidence Score: {display_conf:.1f}%", ln=True)
    
    pdf.ln(5)
    
    # --- AI Reasoning ---
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "3. Clinical Reasoning (Gemini 2.0)", ln=True)
    pdf.set_font("Helvetica", "", 10)
    
    explanation = result_data.get("explanation", {})
    reasoning = explanation.get("reasoning") or explanation.get("gemini_explanation") or "No detailed reasoning available."
    
    pdf.multi_cell(0, 6, reasoning)
    
    pdf.ln(10)
    
    # --- Disclaimer ---
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(100)
    pdf.multi_cell(0, 4, "DISCLAIMER: This report is generated by an AI clinical decision support system. It is intended for healthcare professionals to augment clinical judgment. It is NOT a diagnostic device. Please consult with a specialist for critical medical decisions.")

    return pdf.output()
